name: error_handler
description: error handler for all http client in dart dio, chopper http and more
version: 1.0.4-dev
repository: https://github.com/masreplay/perfect_error_handler
homepage: https://github.com/masreplay/perfect_error_handler

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  http_mock_adapter: ^0.3.3
  lints: ^2.0.0
  test: ^1.16.0

dependencies: { dio: ^4.0.6, freezed_annotation: ^2.1.0, chopper: ^4.0.1 }
